### ISSUE TITLE
Unable to start a single player world in Minetest 5.5.0-win64

### ISSUE THREAD

**Issue by lukasgolson** [ubc-minetest-classroom/Minetest_Classroom#3]
`ModError: Failed to load and run script from G:\minetest-5.5.0-win64 UBC\bin\..\games\Minetest_Classroom\mods\mc_teacher\init.lua:
...\bin\..\games\Minetest_Classroom\mods\mc_teacher/api.lua:7: attempt to index local 'meta' (a nil value)
stack traceback:
	...\bin\..\games\Minetest_Classroom\mods\mc_teacher/api.lua:7: in function 'load_from'
	...bin\..\games\Minetest_Classroom\mods\mc_teacher\init.lua:33: in main chunk
Check debug.txt for details.`

**Mods installed:**
- Minetest Classroom
- Minetest Game

**Reproduction steps:**
1. Clone Minetest_Classroom repo into a fresh Minetest 5.5.0 installation under "/games/" directory
2. Launch the game and (with Minetest Classroom selected as the game), create a new world named "test"; Mapgen selected: V7. Default worldgen flags selected (see attached screenshot). 
3. Bingo! Errors are created.

![image](https://user-images.githubusercontent.com/7264590/167497709-368895a4-dde0-4124-91cb-55fbb215ed4d.png)

**Comment by pauldpickell** [comment]
I fixed the mod storage call in mc_teacher with  #4  and now I cannot reproduce this. Originally, the game was developed with singlenode mapgen, so other mapgens might cause unexpected behavior like `failed to resolve node name 'flowers:mushroom_brown'` because `flowers` is not distributed with the game.

**Comment by lukasgolson** [comment]
> I fixed the mod storage call in mc_teacher with #4 and now I cannot reproduce this. Originally, the game was developed with singlenode mapgen, so other mapgens might cause unexpected behavior like `failed to resolve node name 'flowers:mushroom_brown'` because `flowers` is not distributed with the game.

This makes sense; When using the singlenode mapgen, however, I am still getting the `NodeResolver: failed to resolve node name 'flowers:mushroom_brown' errors. When I get a free moment later, I will look into what might be causing the flower errors.

**Comment by lukasgolson** [comment]
Fixed by defaulting to the singlenode world-type and the realm/classroom system implemented in #1
